trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  major: 0
  patch: $[counter('patch', 0)]

jobs:
- job: MergeAndPush
  displayName: 'Merge dev into main and Push to GitHub'
  steps:
  - checkout: self
    persistCredentials: true
  - script: |
      git pull origin dev  # Pull changes from dev branch
      git config user.email "$(github_user_email)"
      git config user.name "$(github_user_name)"
      git remote add github https://$(github_token)@github.com/andruidb/SilentShuffle.git
      git checkout -b main  # Create and switch to a new local branch named 'main'
      git merge --no-ff dev  # Merge changes from dev into main
      git add .
      # Remove pipeline.yml before committing
      git rm pipeline.yml
      git commit -m "Silent Shuffle v$(major).$(patch)"
      git pull github main --rebase  # Pull changes from GitHub's main branch and rebase local changes
      git push github HEAD:main  # Push changes to GitHub's main branch
    displayName: 'Merge dev into main and Push to GitHub'
