trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  major: 1
  patch: $[counter('patch', 1)]

jobs:
- job: MergeAndPush
  displayName: 'Merge dev into main and Push to GitHub'
  steps:
  - checkout: self
  - script: |
      git config user.email "$(github_user_email)"
      git config user.name "$(github_user_name)"
      git checkout -b main
      git merge --no-ff dev
      git add .
      git commit -m "Silent Shuffle v$(major).$(patch)"
      git push https://$(github_token)@github.com/andruidb/SilentShuffle.git HEAD:main
      git push self HEAD:main
    displayName: 'Merge dev into main and Push to GitHub'