trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  major: 1
  patch: $[counter('patch', 1)]

jobs:
- job: MergeAndPush
  displayName: 'Merge dev into main and Push to GitHub'
  steps:
  - checkout: self
  - script: |
      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"
      git checkout -b main
      git merge --no-ff dev
      git add .
      git commit -m "Silent Shuffle v$(major).$(patch)"
      git push https://$(github_token)@github.com/your_username/your_repository.git HEAD:main
    displayName: 'Merge dev into main and Push to GitHub'