<<<<<<< HEAD
<<<<<<< HEAD
trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  major: 1
  patch: $[counter('patch', 1)]

jobs:
- job: MergeAndPush
  displayName: 'Merge dev into main and Push to GitHub'
  steps:
  - checkout: self
    persistCredentials: true
  - script: |
      git config user.email "$(github_user_email)"
      git config user.name "$(github_user_name)"
      git config pull.rebase true
      git checkout -b main
      git pull origin main
      git merge --no-ff dev
      git add .
      git commit -m "Silent Shuffle v$(major).$(patch)"

      # Configure GitHub credentials
      # git remote set-url origin https://$(github_user_name):$(github_token)@github.com/andruidb/SilentShuffle.git

      git push origin HEAD:main
    displayName: 'Merge dev into main and Push to GitHub'
=======
=======
>>>>>>> 47e40e5 (GOOD Update pkgmeta.yaml for Azure Pipelines)
trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  major: 1
  patch: $[counter('patch', 1)]

jobs:
- job: MergeAndPush
  displayName: 'Merge dev into main and Push to GitHub'
  steps:
  - checkout: self
    persistCredentials: true
  - script: |
      git config user.email "$(github_user_email)"
      git config user.name "$(github_user_name)"
      git config pull.rebase true
      git checkout -b main
      git pull origin main
      git merge --no-ff dev
      git add .
      git commit -m "Silent Shuffle v$(major).$(patch)"

      # Configure GitHub credentials
      # git remote set-url origin https://$(github_user_name):$(github_token)@github.com/andruidb/SilentShuffle.git

      git push origin HEAD:main
<<<<<<< HEAD
    displayName: 'Merge dev into main and Push to GitHub'
>>>>>>> 47e40e5 (GOOD Update pkgmeta.yaml for Azure Pipelines)
=======
    displayName: 'Merge dev into main and Push to GitHub'
>>>>>>> 47e40e5 (GOOD Update pkgmeta.yaml for Azure Pipelines)
